### ISSUE TITLE
Jump cut during zoom transition in Safari on mac and iOS since 2.1.8 update

### ISSUE THREAD

**Issue by wwwonka** [sachinchoolur/lightGallery#1087]
Hey @sachinchoolur.
Not sure if you've seen [my answer](https://github.com/sachinchoolur/lightGallery/issues/1081#issuecomment-876667259) to the previous issue since it got closed.

Basically, since the 2.18 update, the slide transition works great on Safari but a weird "jump cut" issue now happens when I close and reopen the gallery. Again, Firefox and Chrome both work just fine.

[Here](https://user-images.githubusercontent.com/16738328/124975317-e82d4b80-dffb-11eb-9c3f-0a6778b5de78.mp4) is a video capture of it in action.

Any idea of what might be causing this?

**Comment by sachinchoolur** [comment]
Hey @wwwonka,
Sorry, I missed your comment. Just tested on safari 12 or mojave and 12 on catalina. Both work fine for me.

Do you have any custom css applied(maybe easing)? Is it possible for you to share the website link?

**Comment by wwwonka** [comment]
Sure [here](https://main-dev.netlify.app) is the site... big work in progress but if you don't mind having a look.
Scroll down a little, you will see the gallery.

**Comment by sachinchoolur** [comment]
Thanks for the link. But it is working fine for me 😇

Could you please try adding the following CSS into your document and try again?

```css
.lg-outer .lg-inner {
    transition: none !important;
}
```

**Comment by wwwonka** [comment]
The zoom works if I had this line but it cancels the slide transition everywhere now...

**Comment by sachinchoolur** [comment]
Ok. Got it. I'll try to fix this ASAP

**Comment by sachinchoolur** [comment]
Hey,

As a workaround, could you please add the following CSS into your document?

```css
.lg-outer .lg-inner {
    transition: none !important;
}
.lg-outer.lg-css3 .lg-item:not(.lg-start-end-progress).lg-prev-slide, 
.lg-outer.lg-css3 .lg-item:not(.lg-start-end-progress).lg-next-slide, 
.lg-outer.lg-css3 .lg-item:not(.lg-start-end-progress).lg-current {
    /** Change the value if required**/
    transition-duration: 400ms !important;
}
```

I need to change the whole logic of CSS easing and transition duration to make it work for safari 12. ([only 0.08% usage](https://caniuse.com/usage-table))
Can we wait for someone else to confirm the issue as I'm not able to reproduce it?

**Comment by wwwonka** [comment]
@sachinchoolur,

This doesnt work either. The slide transition remains broken in Safari.

I will try setting up a new project to see if I get any luck; I will keep you updated.

**Comment by sachinchoolur** [comment]
Oh, I'm sorry, forgot to add easing.

Please replace with the below CSS

```css
.lg-outer .lg-inner {
    transition: none !important;
}
.lg-outer.lg-css3 .lg-item:not(.lg-start-end-progress).lg-prev-slide, 
.lg-outer.lg-css3 .lg-item:not(.lg-start-end-progress).lg-next-slide, 
.lg-outer.lg-css3 .lg-item:not(.lg-start-end-progress).lg-current {
    /** Change the values if required**/
    transition-duration: 400ms !important;
    transition-timing-function: ease !important;
}
```

Thank you for all your help
