### ISSUE TITLE
Hide thumbnails on fullscreen

### ISSUE THREAD

**Issue by vikneshvijayakumar** [sachinchoolur/lightGallery#1095]
Is there a way to hide thumbnails only on fullscreen? I want to view the image without any distractions when on fullscreen.  hidBarsDelay setting hides only the controls. Is there a way to achieve this manually?

**Comment by sachinchoolur** [comment]
At present, there is no setting to hide thumbnails and captions on fullscreen.

But, you can do it by adding the following CSS rule into your document 

```css
.lg-fullscreen-on {
  .lg-inner {
    top: 0 !important;
    bottom: 0 !important;
  }
  .lg-components {
    transform: translate3d(0, 100%, 0) !important;
  }
}
```


Here is the demo - https://codepen.io/sachinchoolur/pen/yLbzGQG
