### ISSUE TITLE
Configuration for hiding prev/next controls

### ISSUE THREAD

**Issue by raoulb** [sachinchoolur/lightGallery#1107]
A dedicated configuration option for hiding (with time delay) the prev and next controls would be nice to have.
There is the setting [hideBarsDelay](https://www.lightgalleryjs.com/docs/settings/#hideBarsDelay) which does hide these controls but also hides the "top menu bar" where things like maximize and download buttons and the slide index counter are placed which I would like to keep visible all the time.

If this *is already possible*, I could not figure out how. In that case an example in the documentation would be great.

**Comment by sachinchoolur** [comment]
Hey @raoulb,
No, it is not possible to hide controls separately with settings

But you can easily exclude the toolbar from hiding by adding the  following styles

```css
.lg-show-in .lg-outer.lg-hide-items .lg-toolbar {
  opacity: 1;
  transform: translate3d(0, 0, 0);
}
```

Demo - https://codepen.io/sachinchoolur/pen/vYmzmOR
