### ISSUE TITLE
Caption animation and other CSS code not working on my distill site

### ISSUE THREAD

**Issue by ercbk** [sachinchoolur/lightGallery#1125]
I use the R package, [distill](https://github.com/rstudio/distill), to generate the website for my datascience portfolio, and the lightgallery plugins I've used have worked fine which has been great.  

![Screenshot (432)](https://user-images.githubusercontent.com/25374582/129447143-3cc3f272-6641-4a60-b902-d1bb38130baf.png)

It's only when I try to implement the css code for caption animation, dynamic background color, or changing the thumbnail bar location that I run into problems. I'm not sure if the type of site I'm using, or netlify or if I'm screwing up somewhere.  For example, when I try to copy the code for [caption animation](https://codepen.io/sachinchoolur/pen/poebjrm), my image overlaps the caption (problem for lighter colored charts) and the caption animation doesn't work correctly.  

![Screenshot (435)](https://user-images.githubusercontent.com/25374582/129447276-d0448351-c370-4462-a4e3-91bf708e5bd2.png)

Before the caption stayed stationary. Now, it transitions with the image but not how it's supposed to.  

Here is my [gallery page](https://ericbook.netlify.app/gallery.html) where the caption animation code has been used.  
Here is the [RMarkdown script](https://github.com/ercbk/ericbook-distill/blob/master/gallery.Rmd) I use to generate that page.  
This is the [css script](https://github.com/ercbk/ericbook-distill/blob/master/assets/css/gallery.css) for that Rmd.  
This is the [function](https://github.com/ercbk/ericbook-distill/blob/master/R/write-info-html.R) I use to generate the sub-html for the caption.  

I'd appreciate any help you can offer. Thanks.

**Comment by sachinchoolur** [comment]
Hey @ercbk,

Looks like you are directly using scss syntax in the CSS file.

Try replacing the [css](https://github.com/ercbk/ericbook-distill/blob/master/assets/css/gallery.css) content with the following code.
``` css

.lightGallery-captions h4 {
  transform: translate3d(60px, 0, 0px);
}
.lightGallery-captions p {
  transform: translate3d(-60px, 0, 0px);
}
.lightGallery-captions h4,
.lightGallery-captions p {
  opacity: 0;
}

.lg-current .lightGallery-captions h4,
.lg-current .lightGallery-captions p {
  transform: translate3d(0, 0, 0px);
}
.lg-current .lightGallery-captions h4,
.lg-current .lightGallery-captions p {
  opacity: 1;
}

.lg-slide-progress .lightGallery-captions h4 {
  transform: translate3d(-60px, 0, 0px);
}
.lg-slide-progress .lightGallery-captions p {
  transform: translate3d(60px, 0, 0px);
}
.lg-slide-progress .lightGallery-captions h4,
.lg-slide-progress .lightGallery-captions p {
  opacity: 0;
}

.lightGallery-captions h4,
.lightGallery-captions p {
  transition: transform 0.4s ease-in-out, opacity 0.4s ease-in;
}

.lg-current .lightGallery-captions h4,
.lg-current .lightGallery-captions p {
  transition-delay: 500ms;
}
.lg-current.lg-slide-progress .lightGallery-captions h4,
.lg-current.lg-slide-progress .lightGallery-captions p {
  transition-delay: 0ms;
}
```


Also,  you need to wrap `data-sub-html` contant with `.lightGallery-captions` class
```html
<a
        href="img/img1.jpg"
        data-sub-html="<div class='lightGallery-captions'>**<h4>title</h4><p>description</p>**</div>"
    >
        <img src="img/thumb1.jpg" />
</a>
```

Let me know if you face any issues

**Comment by ercbk** [comment]
Thanks,  @sachinchoolur. Sorry for the delay. Everything works great! ...except for zoom. Tried everything I can think of, but since I added the caption animation, it stopped working.

**Comment by sachinchoolur** [comment]
lightGallery does not zoom images beyond their actual size. But this option will be added in the near future.
If you reduce the screen size, you can see the zoom options working.

You can add the below CSS to delay the background color transition.

```css
.lg-backdrop {
    transition: opacity 333ms ease-in 0s, background-color 0.3s ease-in 0.5s;
}
```

Let me know if you face any issues
