### ISSUE TITLE
Add option to make captions not appear on top of images

### ISSUE THREAD

**Issue by gthvidsten** [sachinchoolur/lightGallery#123]
When a caption is displayed for an image it is always displayed on top of the image (with some transparency). There should be an option to prevent this behavior so that captions push the image down.

**Comment by sachinchoolur** [comment]
Hi,
You can do this by adding padding bottom for`.lg-img-wrap ` div.. Value of padding bottom should be the height of `.lg-sub-html` div
``` css
.lg-outer .lg-img-wrap {
     padding-bottom: 70px;
}
```
