### ISSUE TITLE
Thumbnails not working 

### ISSUE THREAD

**Issue by mariashahid** [sachinchoolur/lightGallery#284]
I am unable to get animated or unanimated thumbnails to work in my website as shown in the demo. Please help me setup thumbnails with lightgallery

**Comment by megasent1** [comment]
Maybe you should use a thumbnail plugin together with LightGallery

**Comment by mariashahid** [comment]
Yes I did include it.

**Comment by yroxe** [comment]
Hi, by any chance did you managed to get the animated thumbnails? I got the same problem... Thank you in advance

**Comment by mariashahid** [comment]
I used [Justified Gallery](http://miromannino.github.io/Justified-Gallery/) for thumbnails

**Comment by JElizabeth** [comment]
If i don't include the thumbnails file, everything works fine, but i get no thumbnails.  If i DO include it, the "Skeleton" page shows up (with a space for the thumbnails) but the photos never load.  Using with only photos, no video.  Any advice on getting thumbnails to work?

**Comment by yroxe** [comment]
Aha, thank you...I end up using other application eventually

**Comment by trainerbill** [comment]
I really like this gallery plugin but the demo site is ridiculous.  When you say thumbnails you should really explain that it is the thumbnails AFTER you click on the image.  Furthermore, if you are going to make a demo of your plugin then only use what is available in the plugin.  The fact that you use justifiedGallery without specifying that in the demo is a joke.  I spent over 2 hours trying to get the same hover effect with the little magnifying glass, only to find out that it is some custom CSS and images on your site.  I am absolutely pissed and appalled.  I definitely will not be using this in the future, but hey I have it working now.  For anyone that runs across this in the future here is the CSS from the demo site:

```css
.demo-gallery>ul {
    margin-bottom: 0
}

.demo-gallery>ul>li {
    margin-bottom: 15px
}

.demo-gallery>ul>li a {
    border: 3px solid #FFF;
    border-radius: 3px;
    display: block;
    overflow: hidden;
    position: relative;
    float: left
}

.demo-gallery>ul>li a>img {
    -webkit-transition: -webkit-transform .15s ease 0s;
    -moz-transition: -moz-transform .15s ease 0s;
    -o-transition: -o-transform .15s ease 0s;
    transition: transform .15s ease 0s;
    -webkit-transform: scale3d(1,1,1);
    transform: scale3d(1,1,1);
    height: 100%;
    width: 100%
}

.demo-gallery>ul>li a:hover>img {
    -webkit-transform: scale3d(1.1,1.1,1.1);
    transform: scale3d(1.1,1.1,1.1)
}

.demo-gallery>ul>li a:hover .demo-gallery-poster>img {
    opacity: 1
}

.demo-gallery>ul>li a .demo-gallery-poster {
    background-color: rgba(0,0,0,.1);
    bottom: 0;
    left: 0;
    position: absolute;
    right: 0;
    top: 0;
    -webkit-transition: background-color .15s ease 0s;
    -o-transition: background-color .15s ease 0s;
    transition: background-color .15s ease 0s
}

.demo-gallery>ul>li a .demo-gallery-poster>img {
    left: 50%;
    margin-left: -10px;
    margin-top: -10px;
    opacity: 0;
    position: absolute;
    top: 50%;
    -webkit-transition: opacity .3s ease 0s;
    -o-transition: opacity .3s ease 0s;
    transition: opacity .3s ease 0s
}

.demo-gallery>ul>li a:hover .demo-gallery-poster {
    background-color: rgba(0,0,0,.5)
}

.demo-gallery .justified-gallery>a>img {
    -webkit-transition: -webkit-transform .15s ease 0s;
    -moz-transition: -moz-transform .15s ease 0s;
    -o-transition: -o-transform .15s ease 0s;
    transition: transform .15s ease 0s;
    -webkit-transform: scale3d(1,1,1);
    transform: scale3d(1,1,1);
    height: 100%;
    width: 100%
}

.demo-gallery .justified-gallery>a:hover>img {
    -webkit-transform: scale3d(1.1,1.1,1.1);
    transform: scale3d(1.1,1.1,1.1)
}

.demo-gallery .justified-gallery>a:hover .demo-gallery-poster>img {
    opacity: 1
}

.demo-gallery .justified-gallery>a .demo-gallery-poster {
    background-color: rgba(0,0,0,.1);
    bottom: 0;
    left: 0;
    position: absolute;
    right: 0;
    top: 0;
    -webkit-transition: background-color .15s ease 0s;
    -o-transition: background-color .15s ease 0s;
    transition: background-color .15s ease 0s
}

.demo-gallery .justified-gallery>a .demo-gallery-poster>img {
    left: 50%;
    margin-left: -10px;
    margin-top: -10px;
    opacity: 0;
    position: absolute;
    top: 50%;
    -webkit-transition: opacity .3s ease 0s;
    -o-transition: opacity .3s ease 0s;
    transition: opacity .3s ease 0s
}

.demo-gallery .justified-gallery>a:hover .demo-gallery-poster {
    background-color: rgba(0,0,0,.5)
}

.demo-gallery .video .demo-gallery-poster img {
    height: 48px;
    margin-left: -24px;
    margin-top: -24px;
    opacity: .8;
    width: 48px
}

.demo-gallery.dark>ul>li a {
    border: 3px solid #04070a
}

.home .demo-gallery {
    padding-bottom: 80px
}
```

Your HTML will look something like this:

```html
<div class="col-md-7 demo-gallery">
			<div id="lightgallery">
				<a href="/img/services/truck/1.jpg">
					<img src="/img/services/truck/1.thumb.jpg" />
					<div class="demo-gallery-poster">
              <img src="/img/zoom.png">
          </div>
				</a>
				<a href="/img/services/truck/2.jpg">
					<img src="/img/services/truck/2.thumb.jpg" />
				</a>
			</div>
    </div>
	</div>
```

You can get the magnifying glass here:

http://sachinchoolur.github.io/lightGallery/static/img/zoom.png

Whoever maintains this plugin needs to specify this on the github repo and on the demo site or just write the freaking functionality into the plugin if you are "demoing" it.  Thanks for wasting hours of my life.  If in fact I am incorrect, then I apologize and will remove this comment.
