### ISSUE TITLE
The loading.gif not shown 

### ISSUE THREAD

**Issue by juanlopezdev** [sachinchoolur/lightGallery#390]
Hi,
The plugin works correctly except me showing me an error about not finding the gif " loading.gif " .

``
http://localhost:7001/img/loading.gif 404 (Not Found)
``

In the CSS stylesheet I changed the path where the image points

```css
.lg-outer .lg-item {
  background: url("assets/img/lightgallery/loading.gif") no-repeat scroll center center transparent;
  display: none !important;
}
```

But it has not worked . I also searched if you call the javascript image , but neither I found. 
Greetings from Peru
