### ISSUE TITLE
Hide body scroll

### ISSUE THREAD

**Issue by rorc** [sachinchoolur/lightGallery#395]
Need hide body scroll when gallery is active.

**Comment by abnersajr** [comment]
You only need CSS to do this.
````css
body.lg-on {
    overflow: hidden;
}
```
