### ISSUE TITLE
How to blur the background of each image item in light gallery?

### ISSUE THREAD

**Issue by khaliljan** [sachinchoolur/lightGallery#467]
I use Light Gallery for my website and want to make some customization on it. I want to blur the background image of each and every image items that open in the gallery by using those images in their background-image (in CSS). I posted this issue on [Stock Overflow](http://stackoverflow.com/questions/39846035/how-to-blur-the-background-of-each-image-item-in-light-gallery-specific) also with details but haven't get any contentment yet.
Well, wishing here i find this issue solved.

**Comment by sachinchoolur** [comment]
Sorry for the delayed response. I was on vacation.
You need to change `.lg-backdrops` background image on before each slide transition.

### Javascript
``` javascript
  var $lightgallery = $('#lightgallery');
  $lightgallery.lightGallery();
  var data = $lightgallery.data('lightGallery');
  
  $lightgallery.on('onBeforeSlide.lg', function(event, prevIndex, index){
    var img = data.$items.eq(index).attr('data-src');
    $('.lg-backdrop').css('background-image', 'url('+img+')');
  });
```
### CSS
``` css
.lg-backdrop {
  -webkit-filter: blur(50px);
  -moz-filter: blur(50px);
  -o-filter: blur(50px);
  -ms-filter: blur(50px);
  filter: blur(50px);  
}
```


DEMO: http://codepen.io/anon/pen/YGLYoy
