### ISSUE TITLE
containing the gallery inside an element

### ISSUE THREAD

**Issue by guykatz** [sachinchoolur/lightGallery#499]
hi guys;
I have posted this https://github.com/sachinchoolur/lightgallery.js/issues/52 in the light gallery js github but it seems like this git has more traffic plus i am using jquery :)
I'd appreciate your help.
thanks,

**Comment by sachinchoolur** [comment]
It is not possible with default settings. By default, lightGallery inserts HTML markup into body. You can just find and replace `$('body')` to `$(yourContainer)`.

Also, add the following CSS into your document to get proper alignment

``` css
yourContainer {
  position: relative;
}
.lg-backdrop {
  position: absolute;
}
.lg-outer {
  position: absolute;
}
.lg-outer .lg-item, .lg-outer .lg-img-wrap, .lg-outer .lg-video-cont {
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
}
.lg-sub-html {
  position: absolute
}
```
Here is the demo: http://codepen.io/anon/pen/ZByYwP
