### ISSUE TITLE
Strange rotating bar?!

### ISSUE THREAD

**Issue by Scarwolf** [sachinchoolur/lightGallery#508]
When clicking on an image and showing it in the gallery, I have a strange rotating bar on the right side, I can't find out where it comes from...

http://imgur.com/a/fGcOX

What could this be?!

**Comment by sachinchoolur** [comment]
Are you talking about the background color of control(Next/Prev) buttons?
If yes try adding the following css in your document 
``` css
.lg-actions .lg-next, .lg-actions .lg-prev {
    background-color: transparent;
}
```
