### ISSUE TITLE
Question to option hideBarsDelay

### ISSUE THREAD

**Issue by neoman666** [sachinchoolur/lightGallery#532]
How can I add other elements to the hideBarsDelay option? For the example I would like to hide the element with the class lg-sub-html automatically after 6 seconds of inactivity.

Thanks!

**Comment by sachinchoolur** [comment]
Hello,
You can add the following CSS into your document. 

``` css
.lg-sub-html {
    transition: transform 0.35s cubic-bezier(0, 0, 0.25, 1) 0s, opacity 0.35s cubic-bezier(0, 0, 0.25, 1) 0s;
}

.lg-hide-items .lg-sub-html {
    opacity: 0;
    transform: translate3d(0px, 100%, 0);
}
```

Demo: http://codepen.io/anon/pen/LxGdoY

**Comment by neoman666** [comment]
That's it. Thanks

**Comment by neoman666** [comment]
With option

`thumbnail: true`

it does not work as desired. Do you have a tip for me?

**Comment by neoman666** [comment]
Someone an idea?

**Comment by sachinchoolur** [comment]
Hi @neoman666 ,
Sorry, I missed your comment :)

Add the following lines of css into your document.
``` css
.lg-outer.lg-pull-caption-up .lg-sub-html {
  transition: transform 0.35s cubic-bezier(0, 0, 0.25, 1) 0s, opacity 0.35s cubic-bezier(0, 0, 0.25, 1) 0s, bottom 0.25s ease;
}
```
Demo: http://codepen.io/anon/pen/LxzNEy?editors=0110
