### ISSUE TITLE
Iframe size bug in 2560x1080

### ISSUE THREAD

**Issue by cakama3a** [sachinchoolur/lightGallery#563]
Imposible to scroll iframe page to the 100% bottom in this resolution.

**Comment by sachinchoolur** [comment]
Hi @cakama3a ,
Please try adding the following CSS rules into your document(after lightGallery.css) and let me know the result 

``` css
.lg-outer .lg-video {
    padding-bottom: 0;
    height: 100%;
}

.lg-outer .lg-video-cont {
    height: 100%;
}
```
