### ISSUE TITLE
Adjusting mobile iframe height

### ISSUE THREAD

**Issue by jshapi05** [sachinchoolur/lightGallery#587]
Hi! I was wondering how I can adjust the height of an iframe on mobile to be 100%? Right now, it resizes to display approximately only the middle 1/3 of the screen. Thanks!

**Comment by sachinchoolur** [comment]
Hey @jshapi05,
Yes, it is possible via CSS. The height of frame is controlled by `padding-bottom` property.
``` css
.lg-outer .lg-video {
    padding-bottom: 56.25%
}
```
You can override it it 100% on mobiles 

``` css
.lg-outer .lg-video {
    padding-bottom: 100%;
}
```
let me know if you have any queries
