### ISSUE TITLE
preventing the body to scroll in an i-frame

### ISSUE THREAD

**Issue by snote** [sachinchoolur/lightGallery#798]
How can I achive the body not to scroll when an i-frame is opened over it?
 $('#i-frame').lightGallery({
        selector: 'this',
snote

**Comment by englishextra** [comment]
@snote
```css
/*!
 * fixes to glightbox.fixed.scss
 * @see {@link https://github.com/sachinchoolur/lightGallery/issues/798}
 */

.lg-on {
	overflow: hidden;
	-webkit-overflow-scrolling: touch;
	touch-action: auto;
	height: auto;
}
```
