### ISSUE TITLE
Background Image of lightGallery

### ISSUE THREAD

**Issue by HKBULIB** [sachinchoolur/lightGallery#846]
The background color is black by default.  Can I use a background image instead of using color?

**Comment by sachinchoolur** [comment]
Yes, you can do this by adding the below CSS rule. 
``` css
    .lg-backdrop {
        bacnground-image: url('your-custom-background.jpg');
    }
```
