### ISSUE TITLE
Zoom speed controll

### ISSUE THREAD

**Issue by WeDesIn** [sachinchoolur/lightGallery#987]
Hello guys, 

I am trying to solve one issue allready described here: https://github.com/sachinchoolur/lightGallery/issues/914

The zoom effect on phone device is way too quick for uset to be comfortable. Please check out here: [https://www.gramon.cz/](url)

Is there a way to slow it down? 

Thank you. 

Josef

**Comment by WeDesIn** [comment]
Any ideas please?

**Comment by sachinchoolur** [comment]
Hey @WeDesIn ,
Currently, there is no option for updating zoom transition speed on mobile. 
But, you can do it by adding the following CSS rules into your document 

``` css
.lg-outer.lg-use-transition-for-zoom .lg-item.lg-complete.lg-zoomable .lg-img-wrap, .lg-outer .lg-item.lg-complete.lg-zoomable .lg-image {
transition: transform **1s** cubic-bezier(0, 0, 0.25, 1) 0s, opacity 0.15s !important
}

```

Please let me know if you face any issues
