### ISSUE TITLE
v2 dynamic mode

### ISSUE THREAD

**Issue by niklasp** [sachinchoolur/lightGallery#993]
**Describe the bug**
I am trying v2 beta and following this tutorial for dynamic el: https://sachinchoolur.github.io/lightGallery/v2/demos/dynamic-mode/ but get the error:

```
Uncaught TypeError: can't access property "focus", this.outer.get() is null
    openGallery http://wrappertest.local/wp-content/plugins/eedee-gutenslider/build/gutenslider-front.js?ver=bd77b2511e85a5d325e64abb5a57a8db:3163
```

Am I supposed to add some markup to the page?

**Comment by sachinchoolur** [comment]
Yes, a dom element is necessary for lightGallery to work. This is required for dispatching custom events.

If you don't want to display the element, you can make it invisible to the users.

``` html
<button class="visually-hidden" type="button" id="dynamic-gallery-demo">Open Gallery</button>
```

```css
/** from bootstrap **/
.visually-hidden {
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    padding: 0 !important;
    margin: -1px !important;
    overflow: hidden !important;
    clip: rect(0, 0, 0, 0) !important;
    white-space: nowrap !important;
    border: 0 !important;
}
```


```js

const $dynamicGallery = document.getElementById('dynamic-gallery-demo');
const dynamicGallery = lightGallery($dynamicGallery, {
    dynamic: true,
    dynamicEl: [
        {
            src: 'img/1.jpg',
            thumb: 'img/thumb-1.jpg',
            subHtml: '<h4>Image 1 title</h4><p>Image 1 descriptions.</p>',
        },
        {
            src: 'img/2.jpg',
            thumb: 'img/thumb-2.jpg',
            subHtml: '<h4>Image 2 title</h4><p>Image 2 descriptions.</p>',
        },
        {
            src: 'img/3.jpg',
            thumb: 'img/thumb-3.jpg',
            subHtml: '<h4>Image 3 title</h4><p>Image 3 descriptions.</p>',
        },
    ],
});
dynamicGallery.openGallery(2);
```
